# Holiness

## Holiness is Everything

God is Holy. Nothing---no duty, no law, no morality, no religion---goes beyond holiness. If God asked us to do something that was outside the scope of holiness, he would be asking us to do something beyond what he is. On the other hand, if God accepted something less than holiness from us then his standard would not be holy and he would not be holy. Holiness is the beginning, end, and everything in between of what God is and what God requires us to be. If the sole text of the Bible was "Be holy, because I am holy," that would suffice to show us God's standard. ^[Owen reference needed]

The story of the Bible can be summarized by God looking down on mankind to find anyone who is holy and not seeing a single person, nor a single moment in a single person, nor a single motive in a single moment in a single person lining up with his standard. Then Jesus, comes on the scene, and all of God's heart is completely satisfied in this man who is holy, like how God is holy. Jesus shares this holiness with us. It's his and he gives it to us. There is no other source for it. It has nothing to do with our actions meritoriously speaking. We don't earn it, it is a gift. But without it, we cannot please God in any way. Without holiness, we are filthy. With it, we are clean.

## Ways We Use Holiness

- To speak about the "otherness" or "transcendence" of God
- To speak about the splendor and majesty of God
- To speak about the oneness of God
- To speak about the summation of the attributes of God
- To speak about our conformity to the likeness to God which we have in Jesus together with the various things we do as a result of that "principle" of holiness. In other words holiness is a river and the fruit that is born of that river.
- To speak of a separation unto God of persons or things, e.g. the holy curtains in the tabernacle.


## What Holiness Is Not

If there is one word to get to understand our family's religion it is this one. Yet if there is a more off-putting word to most people, I do not know what it is. I suspect this is a result of the misuse by many of this word to mean one of these other things.

What holiness is not.

- Holiness is not morality
- Holiness is not about performing religious duties
- Holiness has very little to do with our behavior
- Holiness is not avoiding certain sins
- Holiness is not always visible
- We have no power towards holiness at all
- Anything we initiate is not a part of our holiness (born of the flesh)

## Quotes

> He is the eternal spring and only fountain of all holiness; there is nothing of it in any creature but what is directly and immediately from him; there was not in our first creation. He made us in his own image. And to suppose that we can now sanctify or make ourselves holy is proudly to renounce and cast off our principal dependence upon him.

> He is the eternal spring and only fountain of all holiness.

> Holiness is nothing but the implanting, writing, and realizing of the gospel in our souls.

> There neither is, nor ever was, in the world, nor ever shall be, the least dram of holiness, but what, flowing from Jesus Christ, is communicated by the Spirit, according to the truth and promise of the gospel.

> Wherefore holiness, with the fruits of it, with respect unto their proper ends, ... is all that God requireth of us.

> It is one thing to have holiness really thriving in any soul, another for that soul to know it and to be satisfied in it



