# Experimental

## Christianity that only works if...

Most people's religion involves beliefs and practices that would work whether or not God is real. The best religion though is a religion that would not work if God were not real. Think of David or Jonah or Moses. The things they did would not have worked without a real God. That's how we want our religion to be, that is experimental.

## Experimental / Experiential / Sensible

We use the terms experimental, experiential, sensible fairly interchangeably. In all of them, God has to supply the other half of the experiment. We pray, and the prayer in answered---good. We pray and the prayer is not answered---we ask "why?" Perhaps we cherished iniquity in our heart ^[Psa 66:9], perhaps we were not seeking God's kingdom first ^[Matt 6:33, Hag 1:6], perhaps we were not praying according to a promise ^[John 5:17], perhaps is is simply for God's glory that he does not answer ^[John 9:2, 2Cor 12:9]. In any case it is an experiment, the answer to which is a sensible (able to be sensed) experience or lack thereof.

## Not All Religion

This isn't to say everything in Christianity is to be experimental. Sometimes the best kind of faith is a faith that believes when it cannot see ^[John 20:29], but along with that, tasting and seeing that the Lord is good ^[Psa 34:8] is also faith, a faith that is based on the experience of things hoped for.

## Experimental Communion

The area of life this comes into play the most often is looking God's presence. When we look for him and don't find him. That is experimental. When we look for him and find him, that is also experimental. I'll discuss communion with God in another chapter, but it is the heart of true religion and thus true religion must be experimental.

## Regarding Detractors

Lastly, you will run into many people who disagree with this notion. Sometimes the disagreement is merely one of semantics, but more often people disagree with the core claim. To them I quote John 3, "unless one is born again he cannot see the kingdom of God," and both being born again and seeing the kingdom of God are the exact kind of experiences we are asserting as essential.

## Quotes

> Experience is the food of all grace

> Now, he administereth comfort no other way but by giving unto the minds and souls of believers a spiritual, sensible experience of the reality and power of the things we do believe.

> The soul finding not Christ present in his wonted manner, warming, cherishing, reviving it with love, nigh to it, supping with it, always filling its thoughts with himself ... it presently inquires into the cause of all this ... Here it accomplished a diligent search; it considers the love, tenderness, and kindness of the Lord Jesus, what delight he takes in abiding with his saints, so that his departure is not without cause and provocation. “How” saith it, “have I demeaned myself, that I have lost my Beloved? where have I been wandering after other lovers?” And when the miscarriage is found out, it abounds in revenge and indignation.

> As a man that hath a jewel of great price, having no occasion to use it, lays it aside, as he supposes, in a safe place; in an agony and extremity of want going to seek for his jewel, he finds it not in the place he expected, and is filled with amazement, and knows not what to do;—so is it with this pearl of the gospel. After a man hath sold all that he hath for it, and enjoyed it for a season, then to have it missing at a time of need, it must needs perplex him. So was it with the spouse here. “I sought him,” saith she, “but I found him not;” a thing which not seldom befalls us in our communion with Christ.

> It often so falls out in our communion with Christ, when private and public means fail, and the soul hath nothing left but waiting silently and walking humbly, Christ appears; that his so doing may be evidently of grace.

> I shall crave leave to say, that he who hath no experience of spiritual shame and self-abhorrency, upon the account of this inconformity of his nature and the faculties of his soul unto the holiness of God, is a great stranger unto this whole work of sanctification.

> And generally this [ruin or imparing] is so when men content themselves, as was said, with the notions of truth, without labouring after an experience of the power of them in their hearts, and the bringing forth the fruit of them in their lives, on which a decay must needs ensue.
