# Salvation

## Salvation and the Trinity

Every Christian has had to come to grips with the notion of our God being three in one. It is a humbling thing to have to set your hope in a God who you do not understand. I suspect many have not really humbled themselves in this way, but have settled for serving a God who is too understandable, too like them, and thus, too boring ^[There is a link between forgetting God's works and who God is on the one hand, and then becoming weary of God and bored with God on the other hand. This leads to a lack of prayer, a lack of calling on God, a lack of noticing the absence of God. This progression should be thought on more, and I plan to do that in a chapter on the unforgivable sin.] ^[Psa 50:21, Num 23:19, Isa 43:22, Jer 2:13].

If it can be accepted that God is three in one, then it should not be too hard to accept that salvation is also three in one. I could write this better if I knew how much that link was intentional and how much it is accidental, but I'll leave that for you to reason out. What I mean by salvation is three in one is mainly that there is a past, a present, and a future aspect to salvation. But there is not 3 salvations but one salvation. But the 3 are not the parts of salvation but that each aspect of salvation is in actuality the whole thing. Words fail.

I'll take a few stabs at this:

## A Philisophical Approach

In Latin, _Modus Ponens_ means "method of affirming." It is a rule of inference used to draw logical conclusions that states that if p is true, and if $p \rightarrow q$ (read "p implies q"), then q is true. In this case you could say that p is a _sufficient condition_ of q and that q is a _necessary condition_ of p.

### Modus Ponens
If it is a salad, it has vegetables. St.Paul Chop is a salad. Therefore, St.Paul Chop has vegetables.
$$\frac{salad \rightarrow vegetables, salad}{\therefore vegetables}$$


### Modus Tollens
If it is a salad, it has vegetables. Fruit salad does not have vegetables. Therefore, fruit salad is not salad.
$$\frac{salad \rightarrow vegetables, \neg salad}{\therefore \neg vegetables}$$


### Affirming the consequent
If it is a salad, it has vegetables. A BLT has vegetables. Therefore, BLTs are salads.
$$\frac{salad \rightarrow vegetables, vegetables}{\therefore salad}$$

In the above example regarding salads and vegetables. You could say it is necessary for a salad to have vegetables (q is necessary for p). You could also say that eating salad is sufficient for eating your vegetables (p is sufficient for q). Lastly, sometimes things are necessary and sufficient conditions for each other ($p \leftrightarrow q$), but this is not always the case. When people reason wrongly along these lines, they are making the error called "affirming the consequent." For example thinking BLTs are salads because they have vegetables. This would only be true if vegetables are necessary and sufficient for salads, which they are not. But being an unmarried man is both necessary and sufficient for being a bachelor, in this case p implies q and q implies p ($p \leftrightarrow q$).

Easy right?

This can be helpful for Christian reasoning.
For example:

1. ($pleasing \rightarrow believing$) Believing that God exists is necessary for pleasing God, but is belief in God sufficient for pleasing God? No, because even the demons believe.
2. ($grace \rightarrow works$) Grace is sufficient for good works
   
   > God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.

   But do good works always show grace? Can man do good without God? Is it $grace \leftrightarrow works$ or merely $grace \rightarrow works$?
3. ($faith \leftrightarrow salvation$) Faith is both necessary and sufficient for salvation. If we believe we will be saved and no one will be saved who does not believe.

### Salvation as Justification, Sanctification, and Glorification

In our Christianity, we would claim all of the following:

1. Justification is both necessary and sufficient for salvation 
2. Sanctification is both necessary and sufficient for salvation
3. Glorification is both necessary and sufficient for salvation

As a result of thinking this way, we would also say that:
Justification, sanctification, and glorification are all necessary and sufficient for each other.

Going around the Trinity Shield with this would yield: Justification is not Sanctification is not Glorification is not Justification. But Justification is Salvation and Salvation is Justification. Sanctification is Salvation and Salvation is Sanctification. Glorification is Salvation and Salvation is Glorification.

It's a simple concept. But Christians get it wrong often and this leads to problems.

## Analogical Approaches

Another way to look at it is that justification is most related to Jesus, sanctification is most related to the Spirit, and glorification is most related to the Father.

Another way is to say justification is most related to Jesus' work on the cross, sanctification is most related to Jesus' work in his life, and glorification is most related to Jesus' resurrection.

Another way is to say that the Bible speaks of a past, present, and future salvation. 

> For by grace you have been saved. 

> But to us who are being saved. 

> Much more shall we be saved. 

Salvation past is justification, salvation present is sanctification, salvation future is glorification.

Another way is to say that in justification, God declares us just as if we were Christ. In sanctification God both treats us and makes us holy as Christ is holy. In glorification God makes us such partakers of the divine nature that he doesn't have to squint at our holiness anymore. We are made really like Christ in whatever is communicable therein. 

Put it this way: In Adams fall, he gave the middle finger to God. Now we are all born giving the middle finger to God. Christ never did, he loved and obeyed. In justification, God see's us as having put the middle finger down, in sanctification he helps us put our finger down, and in glorification he completes and finalizes the process. This, by the way, is the easiest analogy to see the relationship between works and salvation. How is sanctification tied to works? As the cause not as the result---don't confuse the cart for the horse.

Do not truncate salvation down to a prayer you prayed, or even down just to justification or down to anything else. God is one and likewise, salvation is one. God is three and likewise, accept of no other salvation than one that is all three of these.

## Mistakes

A few examples of common errors may be helpful.

The Pharisees were proud of their past salvation but denied a need for ongoing and future holiness.

The "Holiness Movement" as far as I understand it, saw the need for personal holiness but no such need for a justification in Christ by his work alone that would cause them to actually be sanctified and thus glorified in a way that gave God sole credit for salvation.

The general bulk of humanity believes that God will one day save them when they die, not based on any sort of justification nor sanctification, but merely from God's own goodness, I would liken this to a hope in glorification without a need for the other two.

Charismatics tend to simplify salvation down to justification and justification down to an easy believism. But the important thing for Christian living is a second blessing, or being "activated" or being baptized in the Holy Spirit. Thus they get a lot right in practice while still missing so much. It is worth loving such as these, while also noticing that several of the churches in Revelation are failing because of their toleration of things that ought not be tolerated. Casting a large "salvation" net does not necessarily do God any favors, though it is usually done because of sympathy. Sympathy is a nice man-accomplishable version of holiness that needs no work of God to put on. It is born of the flesh, though thought of as acceptable of God. It is a watermelon, not an apple.

Like Charismatics, Reformed folk tend to also simplify salvation down to justification. It's sometimes amazing how similar reformed churches are to charismatic ones. But while charasmatics tend to err on the side of making their non-salvific sanctification something that God does in us apart from our working, reformers tend toward making their non-salvific sanctification something that we must try had to grow in and accomplish by our working.

## Conclusions, Applications, and Whatnot

All of this is not by our works. Christians tend to get (I hope) that we cannot earn our justification by our works. They tend to be bad at getting that salvation is not by our works either. Glorification then tends to be a mixed bag of earning it and not earning it. Please believe that all of salvation is not by our earning it. Just as there are legalists and Pharisees who look for their justification by works, there are also legalists and Pharisees who demand a sanctification by works. Both are obnoxious, but I think the sanctification legalists might cause the most damage in God's churches. What we do believe is that justification does not _accept_ of our works. It is God's work alone and refuses to us have any part in it. It is _monergistic_. However sanctification does _accept_ of our works. It is a work God does in us, we do have a part in it. It is _synergistic_. This helps me make sense of why it is so easy to get sanctification wrong. It _accepts_ of our works but it is not _by_ our works.

This belongs under a chapter on assurance, but while we are here, I will point out that you have no real access to your justification nor your glorification. You have most access to your sanctification. And thus, your assurance and the proof of your salvation, justification, and glorification are all through your sanctification. Remember that the Holy Spirit is said to be the seal of our salvation, and spiritual sanctification is not different than the Spirit's work in our life.
