# (PART) Part II - More Beliefs not yet written about {-}

# Communion with God
# Mortification
# The Holy Spirit
# The Trinity V
# Seed of Faith
# Church
# A House
# Does it Work for Family
# Old Man / New Man
# Regeneration
# Sovereignty
# Suffering
# Freedom / Liberty
# Fear and Shame
# Discernment
# Marriage / Headship
# Universal Sincerity
# Hell and Zombies
# Cleanness vs Righteousness
# Sanctified Persons vs Sanctified Actions
# Duty

> but to suppose that whatever God requireth of us that we have power of ourselves to do, is to make the cross and grace of Jesus Christ of none effect. Our duty is our duty, constituted unalterably by the law of God, whether we have power to perform it or no, seeing we had so at our first obligation by and unto the law, which God is not obliged to bend unto a conformity to our warpings, nor to suit unto our sinful weaknesses. Whatever, therefore, God worketh in us in a way of grace, he prescribeth unto us in a way of duty, and that because although he do it in us, yet he also doth it by us, so as that the same work is an act of his Spirit and of our wills as acted thereby

# Apostasy
# Assurance
# The Gospel
# Temptation
# First Love
# Fruit
# Questions and Answers

It is difficult to give people answers who do not first have questions

# Impatience
# Finished Righteousness
# Justification and Sanctification as Friends
# Humility
# Today
# The Unforgiveable Sin
# Daily Forgiveness
# Prayer (Promises and Commands)
# Original Sin
# Image of God
# Habitual Grace (skip)
# Evangelical/Reformed/Bapterion Mutts
# Commands and Promises
Commands and promises fit together like peas and carrots

# Duty and Ability
Duty does not imply ability
